[package]
name = "nft_trading-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.nft_trading]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.4"

[dependencies.elrond-wasm-debug]
version = "0.27.4"
